version: "3.1"

services:
    postgresql:
        image: postgres:11.5
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: trades_service